"""Generate build/version_info.txt (PyInstaller Windows VERSIONINFO) from __version__.
Keeps the .exe's Properties -> Details in sync with the app's single version source."""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from incoming_profile_utility import __version__, __build_date__, APP_NAME

parts = (__version__.split(".") + ["0", "0", "0", "0"])[:4]
v = ", ".join(str(int(p)) for p in parts)

TEMPLATE = f'''# -*- coding: utf-8 -*-\n# Auto-generated by tools/make_version_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({v}), prodvers=({v}),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        StringStruct('CompanyName', 'SandBox Semiconductor'),
        StringStruct('FileDescription', '{APP_NAME} - Incoming Profile Utility'),
        StringStruct('FileVersion', '{__version__}'),
        StringStruct('InternalName', 'ProfileStudio'),
        StringStruct('OriginalFilename', 'ProfileStudio.exe'),
        StringStruct('ProductName', '{APP_NAME}'),
        StringStruct('ProductVersion', '{__version__} ({__build_date__})'),
        StringStruct('LegalCopyright', '(c) 2026 SandBox Semiconductor, Inc.')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''

if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "build" / "version_info.txt"
    out.parent.mkdir(exist_ok=True)
    out.write_text(TEMPLATE.encode("ascii", "replace").decode("ascii"))
    print("wrote", out)
